version: "3.9"

services:
  contract-bot:
    container_name: contract-bot
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./generated:/app/generated
