services:
  contract-bot:
    build: .
    container_name: contract-bot
    env_file:
      - .env
    restart: always
    volumes:
      - ./storage:/app/storage
      - ./generated:/app/generated
      - ./templates:/app/templates:ro
